path:  "/media/hao/My Passport/dataset/blimp/Vehicle Classification.v1i.folder"
train: "train"
val: "val"
#test: "test"

#classes names
#replace all class names list with your classes names
names: ['seadan', 'SUV']